[step1] 지하철 정보 관리 기능 PR 요청
next-step/spring-subway pull request #11
Opened 2023-06-16 08:09 UTC by jisoo27

안녕하세요 리뷰어님!
늦은 리뷰 요청이지만 잘 부탁드리겠습니다. 🙇🏻‍♀️

2023-06-26 16:34 UTC, boorownie requested changes
안녕하세요! 리뷰를 맡은 류성현입니다.
리뷰 요청 주신 코드를 확인했습니다. 점점 발전하고 계신게 눈에 보이는거 같아요👍 
몇가지 코멘트 남겼으니 확인해주세요.
특히 static 메서드 부분은 필수 적으로 개선해볼 수 있는 방법을 생각해오세요!ㅎㅎ

2023-06-26 16:34 UTC, boorownie commented on src/main/java/subway/dto/LineResponse.java
>      }
새로운 이름의 정적 팩토리 메서드군요!
혹시 of에서 createResponse로 변경해주신 이유가 있으실까요?

2023-06-26 16:34 UTC, boorownie commented on src/main/java/subway/dto/LineResponse.java
> +        List<Station> stations = SectionService.findAllStation(line.getSections());
스프링 빈 클래스 정적 메서드를 추가하여 다른 클래스에서 사용할 수 있도록 만들어 주셨군요!
사실 스프링 빈 객체에 정적 메서드를 추가하는 것은 여러가지 문제를 야기할 수 있는 포인트로서 잘 사용하지 않는 방식입니다.
(제어의 역전을 우회하고 호출 코드와 해당 스프링 빈 클래스 자체에 의도하지 않은 결합을 초래할 수 있습니다. 즉 IoC 원칙에 위배가 된다는 말 입니다.)

SectionService의 findAllStation 메서드를 정적 메서드가 아닌 일반 메서드로 변경해보시는 것을 추천드립니다.
1. Line 객체의 sections를 이용하여 역 이름을 찾을 수 있도록 리팩터링 하거나
2. Line 객체 외 Stations 정보를 해당 메서드에서 사용할 수 있게 주입을 받거나

2023-06-26 16:34 UTC, boorownie commented on src/main/java/subway/ui/LineController.java
> +//    }
사용하지 않는 코드는 제거해주세요.
혹시 어떤 이유에서 해당 로직을 제거하셨나요?

2023-06-26 16:34 UTC, boorownie commented on src/main/java/subway/dao/LineDao.java
> +        this.sectionDao = sectionDao;
💪

2023-06-26 16:34 UTC, boorownie commented on src/main/java/subway/application/SectionService.java
> +        }
조건문이 중첩되었네요!
조건문이 중첩되지 않게 하려면 어떻게 하면 좋을까요?
그 결과로 분명 뎁스가 얕아질 수 있을 것 같아요.

2023-06-26 16:34 UTC, boorownie commented on src/main/java/subway/application/SectionService.java
> +        }
꼼꼼한 예외 처리 👍

2023-07-01 16:58 UTC, jisoo27 commented on src/main/java/subway/dto/LineResponse.java
>      }
같은 클래스 내에서 static 메서드로 of 라는 메서드명을 사용하고 있어서 createResponse 라고 변경했습니다. 😅

2023-07-01 16:58 UTC, jisoo27 commented on src/main/java/subway/ui/LineController.java
> +//    }
에러가 나는 정확한 이유를 파악하기 위해 잠깐 주석처리 해놓았는데 확인 후 다시 돌려놓지 못했습니다 😅

2023-07-02 00:19 UTC, boorownie approved these changes
피드백 반영 잘 해주셨습니다!
추가 피드백을 남겨 놓았으니 참고해서 다음 단계에서 반영해보세요 :)

2023-07-02 00:19 UTC, boorownie commented on src/main/java/subway/application/SectionService.java
> +        Section section = sectionDao.insert(line.getId(), new Section(upStation, downStation, request.getDistance()));
이 부분의 비즈니스 로직은 구현해주신 것 처럼 서비스 레이어에서 처리할 수 있지만 
도메인 레이어로 분리해서 처리하는것도 좋을 것 같습니다.
일급 컬렉션 객체를 도출하여 해당 객체에 비즈니스 로직의 책임을 위임하는 방법으로 처리할 수 있습니다 :)

2023-07-02 00:19 UTC, merged