Step2: 지하철 노선도 (구간 추가 기능 심화)
next-step/spring-subway pull request #19
Opened 2023-07-20 10:43 UTC by devxb

# 안녕하세요
안녕하세요:) 우아한테크캠프 6기 교육생 이준영 입니다.
업무로 바쁘신 와중에 코드 리뷰 감사드립니다 

# 궁금한 점

### 1. ApplicationService 
ApplicationService는 아래와 같이 domain, controller, repository의 가교 역할만 하도록 설계하기위해 노력했는데, 역할이 잘 분리되었는지 궁금합니다.
```mermaid
flowchart LR

Controller[Controller] --> Service[ApplicationService]
Service --> Domain[Domain]
Service --> Repository[Repository]

```

### 2. 테스트 구조화
1차(java-racingcar), 2차(java-lotto) 과제때는 [`Describe-Context-It`](https://johngrib.github.io/wiki/junit5-nested/) 패턴을 사용해서 테스트를 구조화 했는데, 이번에는 많이 사용되는 `given-when-then` 패턴을 사용해서 테스트를 구조화 하려고 노력했습니다. `given-when-then` 을 사용한 구조화는 처음 도전했는데, 잘 적용된것인지 궁금합니다.

<img width="485" alt="스크린샷 2023-07-20 오후 7 33 09" src="https://github.com/next-step/spring-subway/assets/62425964/34159c06-e16f-4d9e-bc73-66dc3a10fec0">

*_`given-when-then`을 이용한 구조화 사진_*

2023-07-20 13:28 UTC, Laterality requested changes
안녕하세요. 

잘 구현하셨습니다. 남겨드린 코멘트 확인 부탁드려요.

추가로, 코드 양에 비해 커밋이 다소 많게 느껴지는데요.

필요한 변경을 적절한 단위로 나눠서 적용하고 이를 커밋으로 만들어보면 어떨까요?

예를 들어, 기능에 대한 구현과 이에 대하 테스트가 별개의 커밋으로 나뉘어 있는데, 둘을 나눌 필요가 있을까요?

## Q&A

1. 생각하신 "가교 역할"이 무엇인가를 한 번 정의해보시고, 작성하신 서비스 계층이 이를 만족하는지 고민해보시면 되지 않을까요?
2. [마틴 파울러](https://martinfowler.com/bliki/GivenWhenThen.html)에 따르면 given/when/then의 각 부분은 다음과 같은 역할이라고 하는데요. 작성하신 테스트의 각 부분은 이러한 역할을 잘 수행하고 있나요?
    1. **Given**: 지정된 행위를 하기 전의 상태(=사전 조건)
    2. **When**: 지정된 행위를 수행
    3. **Then**: 행위에 의해 일어난 변경 사항에 대한 설명

2023-07-20 13:28 UTC, Laterality commented on src/main/java/subway/advice/GlobalControllerAdvice.java
> +    ResponseEntity<String> catchIllegalArgumentException(IllegalArgumentException illegalArgumentException) {
응답 body에 plain text로 응답할 텐데, 의도하신 걸까요?

2023-07-20 13:28 UTC, Laterality commented on src/main/java/subway/dao/LineDao.java
>                  .withTableName("line")
테이블 이름이 여러군데서 쓰이는데 표기가 제각각이네요(`line`, `Line`, `LINE`).

쿼리를 실행하는 데는 문제 없겠지만 표기를 통일하면 어떨까요?

2023-07-20 13:28 UTC, Laterality commented on src/main/java/subway/domain/LineManager.java
> +public class LineManager {
`Line`과 이 클래스의 차이는 무엇일까요?

2023-07-20 13:28 UTC, Laterality commented on src/main/java/subway/domain/LineManager.java
> +    private final Line line;
쓰이는 곳이 없는 필드는 제거하면 어떨까요?

2023-07-20 13:28 UTC, Laterality commented on src/main/java/subway/domain/Section.java
> +    private Integer distance;
래퍼 타입을 사용할 필요가 있을까요?

2023-07-20 13:28 UTC, Laterality commented on src/main/java/subway/domain/SectionConnector.java
> +    private final BiPredicate<Section, Section> biPredicate;
필드 이름에 역할을 드러내면 어떨까요?

2023-07-20 13:28 UTC, Laterality commented on src/main/java/subway/dto/LineRequest.java
>  public class LineRequest {
`Line`에 대해 무엇을 요청하는 걸까요?

2023-07-20 13:28 UTC, Laterality commented on src/main/java/subway/dto/LineRequest.java
> +    private String upStationId;
`Station`의 ID는 `long` 타입 아닌가요?

2023-07-20 13:28 UTC, Laterality commented on src/main/java/subway/ui/LineController.java
>          return ResponseEntity.badRequest().build();
`SQLException`이 던져지면 BadRequest 상태 코드로 응답하고 있는데요.

1. 응답 상태 코드가 400이라는 건 요청 실패가 클라이언트 책임이라는 걸 의미할텐데, 이 응답으로 클라이언트는 무엇이 문제인지 알 수 있을까요?
2. `SQLException`의 원인이 무조건 클라이언트 책임이라고 볼 수 있을까요?

2023-07-20 13:28 UTC, Laterality commented on src/main/resources/schema.sql
> +    down_station_id bigint not null,
조인에 사용되는 필드인데, 외래키 제약 조건은 추가하지 않아도 될까요?

2023-07-20 13:28 UTC, Laterality commented on src/test/java/subway/DomainFixture.java
> +package subway;
도메인 객체에 대한 픽스쳐라면 도메인 패키지에 두면 어떨까요?

2023-07-20 13:28 UTC, Laterality commented on src/test/java/subway/application/LineServiceTest.java
> +class LineServiceTest {
예외 케이스에 대한 테스트도 추가하면 어떨까요?

2023-07-20 13:28 UTC, Laterality commented on src/test/java/subway/dao/SectionDaoTest.java
> +class SectionDaoTest {
다른 DAO에 대한 테스트는 작성하지 않아도 될까요?

2023-07-22 01:01 UTC, devxb commented on src/main/java/subway/domain/LineManager.java
> +public class LineManager {
410a5b0

좋은 의견 감사드립니다.
다시 보니 `LineManager`와 `Line`을 분리하니, `Line`의 역할이 2군데에 분산되어 있는 느낌이라,` LineManager`를 삭제하고 `Section -> Line` 이 아닌 `Line -> Section` 구조로 도메인을 변경했습니다!
감사합니다.

2023-07-22 01:02 UTC, devxb commented on src/main/java/subway/domain/LineManager.java
> +    private final Line line;
윗 리뷰 `LineManager삭제` 에서 함께 반영했습니다 :)

2023-07-22 01:06 UTC, devxb commented on src/main/java/subway/domain/Section.java
> +    private Integer distance;
10c9c6f

좋은 의견 감사드립니다.

Section의 경우 Builder를 사용하고 있어서, 휴면에러로 distance를 넣어주지 않아, 오동작 하는 상황`(예외가 발생해야 하는데, 0인 상태로 정상 동작)`을 피하고자 래퍼 타입으로 두었습니다.

코드를 다시보니, 이런 경우 예외를 던지는 validation 로직을 확인하고 원시타입으로 변경했습니다!

2023-07-22 01:07 UTC, devxb commented on src/main/java/subway/domain/SectionConnector.java
> +    private final BiPredicate<Section, Section> biPredicate;
9761cd1

꼼꼼히 리뷰해주셔서 감사합니다.
분기를 신경쓰다가 미처 놓친것 같습니다 ㅠㅠ.
수정하여 커밋하였습니다!

2023-07-22 01:25 UTC, devxb commented on src/main/java/subway/dto/LineRequest.java
>  public class LineRequest {
662f000

가장 많은 고민을 한 리뷰 였던것 같습니다. 

저는 
> 유즈케이스마다 입력 모델을 분리해서, 해당 유즈케이스에서 필요하지 않은 값이 들어가거나 각 유즈케이스의 입력 모델이 발전했을때, 영향을 덜 받게 하라

는 의도로 받아들였는데, 의도하신 부분에 맞게 리팩토링을 진행한것인지 조심스러움이 남는것 같습니다.

---

### 고민의 이유

> 유즈케이스 마다 다른 모델을 사용하면 애플리케이션의 복잡성이 높아지는것 아닌가? 단순함의 미덕을 지키기 위해선 어느선까지 분리를 해야하는것인가.

과제 `racing car`, `lotto` 때는 클린 아키텍처를 사용하여 과제를 진행했었는데, 이 당시 `단순함의 미덕` 이라는 리뷰를 해주셔서 `이번 과제에서는 의도적으로 최대한 단순한 구조로 만들어보는 수련을 하자`는 목표를 갖고 진행했습니다. 

_(의도적으로 가졌던것을 `잘`버리는것 또한 굉장히 어렵고 수련이 필요하다고 느꼈습니다.)_

어느 정도까지 분리를 해야 단순하면서 유연한 설계인지 찾아가는 과정에서 가장 많은 고민을 한 것 같습니다.

좋은 리뷰 감사드립니다 !

2023-07-22 01:33 UTC, devxb commented on src/main/java/subway/dto/LineRequest.java
> +    private String upStationId;
f7d55a5

이전에 js에서 number가 2^53까지 밖에 표현 되지 않아, 클라이언트측과 이슈가 발생했던 경험이 있어서, String으로 두었는데, long으로 리팩토링하고 확인해보니 잘 되는것을 확인했습니다 :)

[java script number 2^53](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

2023-07-22 01:37 UTC, devxb commented on src/main/resources/schema.sql
> +    down_station_id bigint not null,
7f4d385

좋은 의견 감사드립니다!
해당부분 추가해 커밋하였습니다.

2023-07-22 01:37 UTC, devxb commented on src/test/java/subway/DomainFixture.java
> +package subway;
1298ce9

좋은 의견 감사드립니다!

해당부분 추가해 커밋하였습니다.

2023-07-22 01:39 UTC, devxb commented on src/test/java/subway/application/LineServiceTest.java
> +class LineServiceTest {
b2d76e7

좋은 의견 감사드립니다.

Service에서 잘못된 입력에 대한 예외처리를 하고있다고 생각해서, 예외처리 위주로 테스트를 보강했습니다 :)

2023-07-22 01:40 UTC, devxb commented on src/test/java/subway/dao/SectionDaoTest.java
> +class SectionDaoTest {
b119d63

좋은 의견 감사드립니다.

기존에 작성되어있는 기반 코드를 너무 믿고 테스트를 작성하지 않았던것 같습니다.
이 부분 또한, 보강하여 커밋했습니다!

2023-07-22 01:42 UTC, devxb commented on src/main/java/subway/dao/LineDao.java
>                  .withTableName("line")
68d66ba

좋은 의견 감사드립니다.

sql 컨벤션은 미처 신경쓰지 못했던것 같습니다. 
이 부분 또한 일관되게 리팩토링했습니다.

2023-07-22 01:45 UTC, devxb commented on src/main/java/subway/advice/GlobalControllerAdvice.java
> +    ResponseEntity<String> catchIllegalArgumentException(IllegalArgumentException illegalArgumentException) {
좋은 의견 감사드립니다.

이 부분 ErrorTemplate을 만들고 반환하는 형식으로 리팩토링 했습니다.

2023-07-22 08:56 UTC, Laterality approved these changes
피드백 잘 반영해주셨습니다.

추가로 크게 수정할 만한 부분은 없어서 머지하도록 하겠습니다.

남겨드린 코멘트는 다음 단계 진행하시면서 참고해주세요.

2023-07-22 08:56 UTC, Laterality commented on src/main/java/subway/application/StationService.java
>      public StationResponse findStationResponseById(Long id) {
이곳의 id가 래퍼 타입일 필요가 있을까요?

2023-07-22 08:56 UTC, Laterality commented on src/main/java/subway/domain/SectionConnector.java
> +enum SectionConnector {
`Section`과의 상호작용을 위해 `Section`에서는 `connectXXX` 메서드를 default 한정자로 공개하고 있는데요. `SectionConnector`의 로직이 `Section`의 기능에 강하게 결합돼 있다는 건, `SectionConnector`의 기능이 `Section` 내에 위치해야 한다는 신호는 아닐까요?

2023-07-22 08:56 UTC, Laterality commented on src/main/java/subway/ui/StationController.java
> +        return new ResponseEntity<>(ErrorTemplate.of("SQL fail"), HttpStatus.INTERNAL_SERVER_ERROR);
서버에서 오류가 발생했다면 처리되지 않은 케이스가 있다는 의미이고, 급하든 급하지 않든 개발자가 원인을 찾아 수정해야 할텐데요. 원인 파악과 해결에 필요한 정보가 충분할까요?

2023-07-22 08:56 UTC, merged