지하철 노선도 Step 1, 2 구현
next-step/spring-subway pull request #25
Opened 2023-07-20 16:11 UTC by gunner6603

안녕하세요! 지하철 노선도 미션 Step 1, 2 구현 완료했습니다.

도메인 요구사항은 아래와 같습니다.

### 지하철 역 (Station)
지하철 역 하나의 정보

### 지하철 구간 (Section)
지하철 (상행 방향)역과 (하행 방향)역 사이의 연결 정보

- [x] 길이가 양수여야 한다
- [x] 상행역과 하행역은 같을 수 없다
- [x] 자신의 하행역과 주어진 구간의 상행역이 같은지 확인한다.
- [x] 추가할 구간의 크기가 같거나 큰 경우 합칠 수 없다.
- [x] 구간의 상행역과 추가할 구간의 상행역이 같은 경우 합친다.
- [x] 구간의 하행역과 추가할 구간의 하행역이 같은 경우 합친다.
- [x] 구간의 상행역, 하행역이 추가할 구간의 상행역, 하행역과 모두 같거나 모두 다른 경우 합칠 수 없다.

### 지하철 구간들 (Sections)
지하철 구간 리스트를 포장하는 일급 컬렉션

- [x] 상행 종점역과 하행 종점역만 있는 경우(구간이 1개인 경우)인데 삭제 시 예외 발생시킨다
- [x] 삭제할 역이 노선의 하행 종점역이 아니면 삭제할 수 없다
- [x] 끊어진 구간들로 생성할 수 없다
- [x] 순환된 구간으로 생성할 수 없다.
- [x] 널이거나 비어 있는 구간 리스트로 생성할 수 없다.
- [x] 추가할 구간의 한 역만 기존 노선에 포함되어야 한다.
- [x] 노선의 특정 구간과 상행역만 같은 경우 노선에 추가한다.
- [x] 노선의 특정 구간과 하행역만 같은 경우 노선에 추가한다.
- [x] 추가할 구간의 하행역이 기존 노선의 상행 종점역과 같은 경우 노선의 맨 앞에 추가한다.
- [x] 추가할 구간의 상행역이 기존 노선의 하행 종점역과 같은 경우 노선의 맨 뒤에 추가한다.

### 지하철 노선 (Line)
지하철 구간의 모음으로 구간에 포함된 지하철 역의 연결 정보

### 지하철 노선 구간 (LineSections)
특정 지하철 노선에 속하는 구간들을 관리함

- [x] 노선을 생성할 때 한 구간을 생성한다.
- [x] 구간들이 특정 노선에 속하는지 확인한다.
- [x] 다른 노선에 속한 구간들로 생성할 수 없습니다.

2023-07-21 08:51 UTC, fucct requested changes
안녕하세요 :) 

복잡한 로직이었는데 잘 작성해 주셨습니다.
다만, 로직이 LineSections -> Sections -> Section 등으로 분산되어 있어 추적하기 쉽지 않은 코드라는 생각이 드네요.
가장 먼저 LineSections를 없애보는건 어떨까 싶어요. 특별히 정의되 필요가 있는지에 대해 의심이 드는 도메인 객체입니다.  
그 외에 내용에 대해서는 코멘트에 남겨놓았으니 한번 확인 부탁드립니다.

혹시나 모르시는 내용 있으시면 질문주세요 :)

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/domain/LineSections.java
> +    private final Sections sections;
LineSections는 Line과 Sections를 가지고있고, Sections는 List<Section>, Section은 다시 Line을 가지고 있군요. 순환참조와 같은 문제가 발생할 수 있을것 같습니다.

도메인 구조를 좀 더 명확하게 가져가시면 좋을것 같아요!

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/domain/LineSections.java
> +        return sections.add(new Section(this.line, section));
도메인 객체는 항상 온전한 상태로 전달되어야해요. 
불온전한 Section을 파라미터로 받아서 다시 Section을 만들어주는 형태는 도메인 객체를 신뢰할 수 없게 합니다.

Service단계에서부터 온전한 Section객체를 만들어주세요!

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/domain/Section.java
> +    public boolean canPrecede(Section other) {
isUpperSection같은 네이밍은 어떠띾요?

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/domain/Station.java
>      public boolean equals(Object o) {
equals&hashcode 재정의시 항상 꼭 필요할때만 사용하셔야합니다. 

또한 엔티티는 id를 기준으로 동등여부를 따지는게 기본아닐까요?

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/ui/LineController.java
> +    public ResponseEntity<Void> addSection(@PathVariable Long id, @RequestBody SectionAdditionRequest sectionRequest) {
요청에 @Valid 를 적용하면 좋을것 같네요

2023-07-21 08:51 UTC, fucct commented on src/main/resources/schema.sql
> +    distance int,
foreign key 를 안거신 이유가 있을까요?

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/application/SectionsService.java
> +        Section section = createNewSectionBy(request);
도메인객체는 검증이 모두 끝나고 나서 생성되는게 좋습니다.

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/vo/SectionAdditionResult.java
> +package subway.vo;
해당 객체는 무얼위해 VO로 정의하셨나요?

진짜로 VO가 맞나요?

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/vo/SectionAdditionResult.java
> +    private final Optional<Section> sectionToRemove;
Optional을 필드로 선언하는건 안티패턴입니다. 

https://sungminhong.github.io/java/optional/

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/application/SectionsService.java
> +        SectionAdditionResult sectionAdditionResult = lineSections.add(section);
단순히 값만들고 있는 객체를 정의하시기 보단, 역할과 책임이 있는 객체를 만드셔야 객체지향적인 애플리케이션이 됩니다.

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/application/SectionsService.java
> +        LineSections lineSections = sectionDao.findAllByLine(line);
LineSection 내에 요청의 station들이 들어있는지도 검증해야하지 않을까요?

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/domain/Sections.java
> +    private void validateOneInOneOut(Section section) {
메서드는 한가지일만 해야됩니다. 지금은 2개의 station이 들어있는지 없는지를 보고있네요

2023-07-21 08:51 UTC, fucct commented on src/test/java/subway/domain/SectionsAddTest.java
> +class SectionsAddTest {
Sections의 모든 메서드를 테스트하셔야합니다. private 메서드가 포함되어있으면 그걸 호출하는 내용까지 커버되어야합니다

2023-07-21 08:51 UTC, fucct commented on src/test/java/subway/integration/IntegrationTest.java
>  public class IntegrationTest {
이 클래스가 필요한가요?

2023-07-21 08:51 UTC, fucct commented on src/main/java/subway/application/SectionsService.java
> +public class SectionsService {
Service에 대한 테스트도 반드시 작성해주셔야합니다.

2023-07-22 05:51 UTC, gunner6603 commented on src/main/java/subway/domain/LineSections.java
> +    private final Sections sections;
넵 LineSections를 없애는 방향으로 리팩토링 진행해 보겠습니다!

2023-07-22 05:52 UTC, gunner6603 commented on src/main/java/subway/domain/Section.java
> +    public boolean canPrecede(Section other) {
넵 해당 메서드명이 좀 더 직관적인 것 같습니다! 변경해 보겠습니다!

2023-07-22 05:55 UTC, gunner6603 commented on src/main/resources/schema.sql
> +    distance int,
외래키가 걸려 있으면 제약조건 검증으로 인해서 성능과 개발 편의성이 떨어진다는 글을 본 적이 있어서 걸지 않았는데, 애플리케이션 특성상 성능으로 인한 문제는 발생하지 않을 것 같아서 외래키를 추가하는 것이 좋을 것 같습니다. 이 부분도 변경하겠습니다!

2023-07-22 06:15 UTC, gunner6603 commented on src/main/java/subway/vo/SectionAdditionResult.java
> +package subway.vo;
VO에 대해 찾아보니, 도메인 개념을 반영하는 불변 객체로서, 유효성 검증 로직을 가지고, identity에 기반하지 않는 동일성 비교를 수행한다고 되어 있어서, `SectionAdditionResult`는 VO와 거리가 먼 것 같습니다.

2023-07-22 06:16 UTC, gunner6603 commented on src/main/java/subway/vo/SectionAdditionResult.java
> +    private final Optional<Section> sectionToRemove;
넵 해당 부분 변경 진행하겠습니다!

2023-07-22 06:19 UTC, gunner6603 commented on src/main/java/subway/domain/Sections.java
> +    private void validateOneInOneOut(Section section) {
넵 해당 메서드는 구간의 한 역만 노선에 포함되는지 확인하는 메서드인데 내부에서 두 가지 일을 동시에 하고 있어서 메서드를 더 작은 단위로 분리해 보겠습니다!

2023-07-22 06:55 UTC, gunner6603 commented on src/main/java/subway/domain/Station.java
>      public boolean equals(Object o) {
넵 엔티티 비교 시 id만을 사용하도록 하고, 필요한 경우에만 equals와 hashcode를 재정의 하겠습니다!

2023-07-22 07:43 UTC, gunner6603 commented on src/main/java/subway/domain/LineSections.java
> +        return sections.add(new Section(this.line, section));
넵 이 부분은 LineSections를 제거하니 자연스럽게 해결된 것 같습니다!

2023-07-22 07:47 UTC, gunner6603 commented on src/main/java/subway/application/SectionsService.java
> +        LineSections lineSections = sectionDao.findAllByLine(line);
LineSection은 삭제하였고, Sections 내부에 요청 station 중 하나가 들어있는지 확인하는 로직이 존재합니다!

2023-07-22 10:26 UTC, gunner6603 commented on src/main/java/subway/ui/LineController.java
> +    public ResponseEntity<Void> addSection(@PathVariable Long id, @RequestBody SectionAdditionRequest sectionRequest) {
넵 validation 적용해 보겠습니다!

2023-07-22 12:31 UTC, gunner6603 commented on src/test/java/subway/integration/IntegrationTest.java
>  public class IntegrationTest {
이 부분은 뼈대 코드에 포함되어 있던 부분인데요. 제가 알아본 바로는 통합 테스트의 경우 `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)`를 사용해서 실제로 톰캣을 띄워서 테스트를 진행하고, 이때 DB 자동 롤백이 되지 않기 때문에 컨텍스트 재생성을 위해 `@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)`를 사용하는 것 같습니다. 실제로 두 어노테이션 중 하나라도 빠지면 테스트가 정상적으로 수행되지 않습니다.
DB 초기화를 위해 컨텍스트 재생성을 매번 진행하면 시간이 많이 소요되기 때문에 대안으로 테스트가 끝날 때마다 모든 DB 데이터를 삭제하는 방법도 있는 것으로 알고 있는데, 해당 방법을 사용하면 작성해야 하는 코드가 늘어날 것 같습니다. 혹시 `IntegrationTest` 클래스를 사용하지 않고 통합 테스트를 수행하는 좋은 방법이 있을까요?

2023-07-22 12:48 UTC, gunner6603 commented on src/main/java/subway/application/SectionsService.java
> +        Section section = createNewSectionBy(request);
`lineSections.add(section)`가 호출되어야 해당 메서드 내부에서 구간이 추가될 수 있는지 검증이 되기 때문에 현재 코드 상으로는 검증 전에 Section 도메인 객체가 생성되어야 하는 상황입니다.
검증이 끝나고 나서 도메인 객체를 생성하기 위한 방법을 고민해 봤는데, line, upStation, downStation, distance 정보를 lineSections에 넘겨서 구간이 추가되는지 검증하고, 추가가 가능하면 그때 Section 객체를 만드는 방법이 있을 것 같습니다. 이 방법을 사용하면 기존 add 메서드 내부에서 Section 객체 간 상호작용으로 추상화된 로직들을 사용하지 못하게 되고, 넘겨주는 인자가 너무 많다는 생각이 듭니다. 혹시 더 나은 방법이 있을까요?

2023-07-22 12:50 UTC, gunner6603 commented on src/main/java/subway/application/SectionsService.java
> +public class SectionsService {
넵 해당 테스트도 추가하겠습니다!

2023-07-22 12:51 UTC, gunner6603 commented on src/test/java/subway/domain/SectionsAddTest.java
> +class SectionsAddTest {
넵 알겠습니다!

2023-07-22 13:24 UTC, gunner6603 commented on src/main/java/subway/application/SectionsService.java
> +        SectionAdditionResult sectionAdditionResult = lineSections.add(section);
해당 객체가 VO가 아니라는 건 이해가 되는 것 같습니다!

다만 해당 객체의 책임을 생각해 보면 `add 메서드의 결과인 삭제해야 할 구간과 저장해야 할 구간을, 서로 구분 가능한 형태로, 도메인으로부터 DAO로 전달한다` 정도인 것 같은데 이건 객체의 책임으로 보기 어려울까요?

2023-07-23 10:54 UTC, gunner6603 commented
피드백 주신 내용 가능한 만큼 반영해서 수정해 보았습니다.
변경한 내용은 다음과 같습니다.

- LineSections 삭제
- 엔티티 비교시 id 기준으로 비교하도록 변경
- `@Valid`를 사용해서 기본적인 검증(널값이 들어오는지 여부)을 컨트롤러 단에서 수행하도록 변경
- DB 테이블에 외래키 제약조건 추가
- SectionAdditionResult 삭제
- add 메서드가 SectionAdditionResult 대신 업데이트 대상 구간을 반환하도록 변경
  - SectionDao에 업데이트 메서드 추가
- 작성한 서비스 메서드에 대한 테스트 추가

2023-07-23 10:56 UTC, gunner6603 commented on src/main/java/subway/application/SectionsService.java
> +        SectionAdditionResult sectionAdditionResult = lineSections.add(section);
이 부분은 add 메서드가 업데이트 대상 구간을 반환하도록 변경해서 `SectionAdditionResult`를 아예 사용하지 않는 방향으로 수정해 보았습니다!

2023-07-24 13:00 UTC, fucct commented on src/main/resources/schema.sql
> +    distance int,
요부분은 꼭 추가하라는 의견은 아니였고, foreign key에 대한 문제를 정확히 인지하시고 계신지 궁금했습니다 ㅎㅎ

2023-07-24 13:03 UTC, fucct commented on src/main/java/subway/application/SectionsService.java
> +        Section section = createNewSectionBy(request);
제 의견은 이런내용이였어요. 

1. LineSection에 request에 포함된 Station이 모두 존재하는지 확인한다. (요청에 대한 사전 검증)
2. Section 생성시 생성 불가능한 경우에 예외 (도메인 객체 생성에 대한 검증)
3. 기타 검증 (추가 검증)

이런식으로 나눈다면 말씀하신 문제점을 피하고 검증할 수 있지 않을까 했거든요!

2023-07-24 13:05 UTC, fucct commented on src/test/java/subway/integration/IntegrationTest.java
>  public class IntegrationTest {
@BeforeEach로 repository를 모두 deleteAll() 하시는 방법은 어떨까요?

2023-07-24 13:19 UTC, fucct approved these changes
안녕하세요 :) 

리뷰를 일부러 자세한 설명 없이 드렸는데도, 반영을 훌륭하게 잘해주셨습니다!
코드 가독성은 이미 훌륭하고, 디테일한 부분만 몇개 코멘트 남겨드렸어요! 
크게 영향을 미칠 내용은 아니기 때문에 먼저 머지하도록 하겠습니다 :) 다음 미션에서 함께 반영부탁드릴게요!  

궁금하신 부분이 있으시다면 언제든 질문주세요!

2023-07-24 13:19 UTC, fucct commented on src/main/java/subway/application/SectionService.java
> +        sections.add(section).ifPresent(sectionDao::update);
LineSection을 깔끔하게 제거해주신것 같아요.
 다만 add() 메서드의 리턴이 있다는게 약간 가독성을 해치는것 같아요.
 
코드를 처음봤을때 add 시 어떤 객체가 나올지 예상이 될까요?

어떤 경우에 update 되는지도 알 수 없을것 같아요.

2023-07-24 13:19 UTC, fucct commented on src/main/java/subway/domain/Sections.java
> +        return this.values.get(this.values.size() - 1);
CollectionUtils.lastElement() 를 이용해보세요 ~

2023-07-24 13:19 UTC, fucct commented on src/main/java/subway/domain/SectionChange.java
> +public class SectionChange {
사용되지 않는 클래스는 지워주세요!

2023-07-24 13:19 UTC, fucct commented on src/test/java/subway/domain/SectionsTest.java
> +
테스트에서 필드를 공유하는것은 번거로움을 덜지만, 단위테스트 의미에 부합하지 않아요. 

단위테스트는 매 테스트마다 상황이설정되고 상황에 대한 행위를 시도했을때의 결과가 모두 독립적이어야합니다.

2023-07-24 13:19 UTC, merged