Step3: 구간 제거 기능 심화
next-step/spring-subway pull request #31
Opened 2023-07-25 05:58 UTC by devxb

# 안녕하세요
안녕하세요.
1,2차 꼼꼼한 리뷰 감사드립니다 :)

## 구현사항
- 노선의 `앞`, `중간`, `뒤` 구간을 제거하는 기능을 구현했습니다.

## 이전리뷰
- 이전에 리뷰해주신 내용에 대한 변경은 다음과 같습니다.

1. [이곳의 id가 래퍼 타입일 필요가 있을까요?](https://github.com/next-step/spring-subway/pull/19#discussion_r1271270728)
	- 수정 커밋 : 8da35b9165643036327669656538bc272862659d

2. [Section과의 상호작용을 위해 Section에서는 connectXXX 메서드를 default 한정자로 공개하고 있는데요. SectionConnector의 로직이 Section의 기능에 강하게 결합돼 있다는 건, SectionConnector의 기능이 Section 내에 위치해야 한다는 신호는 아닐까요?](https://github.com/next-step/spring-subway/pull/19#discussion_r1271270750)
	- 수정 파일 :[ src/main/java/subway/domain/Section.java](https://github.com/next-step/spring-subway/compare/devxb...devxb:spring-subway:step3#diff-0dccabc01ef83e557faf1e4c6a8fea93e8dc7fd31fa89fa60446e703d49fda2e)
	- 고민 포인트 : 여러가지 방법을 생각해보다, `전략패턴으로의 리팩토링`과 `if문을 사용한 분기처리` 방법중 고민했습니다. 이 상황에서는 분기가 많지 않고, 지하철의 구간을 연결, 해제 하는 경우의 수가 더 늘어날 확률이 적을거 같아서, if문을 사용하되, 가독성을 높이는 방식으로 리팩토링 하였습니다.

3. [서버에서 오류가 발생했다면 처리되지 않은 케이스가 있다는 의미이고, 급하든 급하지 않든 개발자가 원인을 찾아 수정해야 할텐데요. 원인 파악과 해결에 필요한 정보가 충분할까요?](https://github.com/next-step/spring-subway/pull/19#discussion_r1271270755)
	- 수정 커밋 : 91558205418e1a4e11252b603fc2f9270d47603d

2023-07-25 09:50 UTC, Laterality requested changes
안녕하세요.

빠르게 구현하셨네요 👍 

크게 수정이 필요한 부분은 없어보입니다. 남겨드린 코멘트 확인해주세요.

2023-07-25 09:50 UTC, Laterality commented on src/main/java/subway/domain/Line.java
>      public List<Section> getSections() {
`Section`이 가변 객체가 되면서 `Collections.unmodifiableList`만으로는 내부 필드에 대한 접근을 막지 못하겠네요. `Line` 외부에서 내부 `sections`를 변형하는 것을 막으려면 어떻게 하면 좋을까요?

2023-07-25 09:50 UTC, Laterality commented on src/test/java/subway/domain/LineTest.java
> +            assertThat(result.getDeletedSection()).isEqualTo(upSection);
`line` 내부의 구간들의 상태는 확인하지 않아도 될까요?

2023-07-25 09:50 UTC, Laterality commented on src/test/java/subway/domain/SectionTest.java
> +            assertThat(result.getUpdatedSections()).containsExactly(upSection, downSection);
역이 제거된 후 연결된 구간의 거리도 확인하면 어떨까요?

2023-07-25 09:50 UTC, Laterality commented on src/test/java/subway/integration/LineIntegrationTest.java
> +        assertIsBadRequest(response);
우연히 다른 오류와 겹쳐서 의도한 예외가 아닌 다른 예외로 400을 응답할 수도 있을텐데요. 이런 상황은 어떻게 검증할 수 있을까요?

2023-07-26 06:14 UTC, devxb commented on src/test/java/subway/integration/LineIntegrationTest.java
> +        assertIsBadRequest(response);
18e6bb4

좋은 의견 감사합니다.

ErrorMessage에 CustomStatusCode 를 추가하고, 인수테스트에서 해당 CustomStatusCode를 기반으로 예상한 예외가 응답되는지 검증하는 방식으로 리팩토링 했습니다 :)

2023-07-26 06:16 UTC, devxb commented on src/test/java/subway/domain/SectionTest.java
> +            assertThat(result.getUpdatedSections()).containsExactly(upSection, downSection);
ca03188

중간에 있는 역을 삭제할 경우, 거리가 합쳐지는 상황 테스트를 추가했습니다 :)

2023-07-26 06:17 UTC, devxb commented on src/main/java/subway/domain/Line.java
>      public List<Section> getSections() {
bdd1f52

1차적으로 Line에서 List.copyOf로 내부 객체를 복사해서 전달하는 방식으로 리팩토링 하였고,
2차적으로 Section의 public, package-private 메소드가 전부 깊은 복사로 동작하게끔 리팩토링 했습니다 :)

2023-07-26 06:23 UTC, devxb commented on src/test/java/subway/domain/LineTest.java
> +            assertThat(result.getDeletedSection()).isEqualTo(upSection);
93aa171

Line이 갖고있는 Sections 필드의 상태에 대해서도 검증을 해야했는데, Section로 검증이 된다 생각해서 간과한거 같습니다.

이 부분 추가해서 커밋 했습니다! :)

2023-07-26 11:43 UTC, Laterality approved these changes
피드백 잘 반영해주셨습니다.

이번 단계는 머지하도록 하겠습니다.

남겨드린 코멘트는 다음 단계 진행하시면서 참고해주세요.

2023-07-26 11:43 UTC, Laterality commented on src/main/java/subway/domain/Line.java
>      public List<Section> getSections() {
아래 테스트 코드는 여전히 실패하네요.

```java
    @Test
    void sections_must_not_be_modified_outside() {
        // given
        Station upStation = new Station(1L, "upStation");
        Station middleStation = new Station(2L, "middleStation");
        Station downStation = new Station(3L, "downStation");

        Section upSection = DomainFixture.Section.buildWithStations(upStation, middleStation);
        Section downSection = DomainFixture.Section.buildWithStations(middleStation, downStation);

        Line line = new Line("line", "red", new ArrayList<>(List.of(upSection, downSection)));

        line.getSections().get(0).disconnectStation(middleStation);
        assertThat(line.getSections()).hasSize(3);
    }
```

`Liest.copyOf`는 리스트 객체를 복사하는 것 뿐, 리스트의 요소(element)까지 복사하진 않습니다.

```java
    @Test
    void elements_must_not_same() {
        Foo foo = new Foo();
        List<Foo> originList = List.of(foo);
        List<Foo> copiedList = List.copyOf(originList);

        assertThat(originList.get(0)).isNotSameAs(copiedList.get(0));
    }

    private static class Foo {
        public Foo() {
        }
    }
```

2023-07-26 11:43 UTC, merged