Step3 : 구간 제거 기능 심화
next-step/spring-subway pull request #33
Opened 2023-07-25 08:22 UTC by impati

## 1 , 2 단계 리뷰 반영
- `Fixture` 는 데이터 생성하는 역할만 가지고 테스트에서 Dao 를 이용하여 저장하도록 변경
- 구간 추가 성공시 리소스 위치에 대한 정보가 클라이언트 입장에서 필요 없다고 생각해서 구간 추가 시 성공했다는 상태 코드만 응답하도록 변경
- IllegalStateException 에러일 때 메시지를 전달하고 서버 오류로 처리
- `id`  가 있는 생성자는 영속화되었을 때 사용 , `id` 가 없는 생성자는 영속화 되지 않았을 때 사용
- 서비스 레이어에서 더티 체크 관심사를 제거하고 DAO 에서 하도록 변경
- `id` 값을 primitive 값으로하면 없는 값에 대해 0으로 동작하여 잘못된 상황이 발생했을 때 오류없이 동작하지만 오류를 발견하기 어렵다는 문제가 있다고 생각합니다. 그래서 잘못된 상황이 발생했을 때에 잘못된 값이 사용 되기전에 오류를 발생시켜 대응할 수 있도록 `id` 는 래퍼 타입으로 사용했습니다.

# 3 단계 구현
- Sections 에서 deleteSection 메서드를 호출하고 변경된 사항을 Dao 에서 반영합니다
- deleteSection 에서 분기문을 간소화 하는 것보다 케이스별로 어떠한 행동을 하는지 나타내고 싶어서 다음과 같이 구현하였습니다.

```java
public void deleteSection(final Station station) {
        validateDeleteConstraint();
        throwIfNotContain(station);
        removeIfMatchFirstSection(station);
        removeIfMatchLastSection(station);
        removeIfMatchMiddleSection(station);
}
```
- update , delete 수행 시 id 로 먼저 해당 Entity 가 있는지 확인하고 처리하기위해 findById() 를 먼저 호출하도록 변경

2023-07-25 10:11 UTC, Laterality requested changes
안녕하세요.

잘 구현하셨습니다 👍 

테스트만 조금 개선해보면 좋겠네요. 코멘트 확인해주세요.

2023-07-25 10:11 UTC, Laterality commented on src/main/java/subway/error/SubWayExceptionHandler.java
> +                .body(ErrorResponse.of(INTERNAL_SERVER_ERROR.value(), exception.getMessage()));
서버 내부 오류인 경우에는 예외 메시지에 비공개 파라미터나 DB 쿼리처럼 다소 민감한 정보가 포함될 수 있습니다. 이런 경우에는 적당한 오류 메시지로 응답하고 추후 예외 발생 지점과 원인을 파악할 수 있는 정보를 로그로만 남기는 것이 좋습니다.

2023-07-25 10:11 UTC, Laterality commented on src/test/java/subway/application/SectionServiceTest.java
> +    @DisplayName("지하철 노선에 등록된 제거할 수 있다")
무엇을 제거할 수 있을까요?

2023-07-25 10:11 UTC, Laterality commented on src/test/java/subway/domain/SectionsTest.java
>      void A_D_B_C() {
테스트 이름에는 가급적 테스트하고자 하는 기능, 테스트 조건(상황), 의도한 결과가 드러나도록 작성해주세요.

e.g. ID로 노선 조회시 ID가 일치하는 노선이 존재하지 않으면 예외를 던진다

2023-07-25 10:11 UTC, Laterality commented on src/test/java/subway/domain/SectionsTest.java
> +        assertThat(result).hasSize(2);
삭제된 후 구간의 거리도 확인하면 어떨까요?

2023-07-26 05:26 UTC, impati commented on src/main/java/subway/error/SubWayExceptionHandler.java
> +                .body(ErrorResponse.of(INTERNAL_SERVER_ERROR.value(), exception.getMessage()));
SQL 예외의 경우 이를 인지하고 로그만 남겼는데 서버 예외의 경우에도 그래야겠다는 것을 깨달았습니다!

2023-07-26 05:26 UTC, impati commented on src/test/java/subway/application/SectionServiceTest.java
> +    @DisplayName("지하철 노선에 등록된 제거할 수 있다")
테스트 네임을 전체적으로 리팩토링했습니다.

2023-07-26 05:26 UTC, impati commented on src/test/java/subway/domain/SectionsTest.java
>      void A_D_B_C() {
테스트 네임을 전체적으로 리팩토링했습니다.!

2023-07-26 05:27 UTC, impati commented on src/test/java/subway/domain/SectionsTest.java
> +        assertThat(result).hasSize(2);
이 부분의 테스트를 놓쳤던 것 같습니다. 테스트 추가를 진행했습니다!

2023-07-26 05:35 UTC, impati commented
# 3단계 리뷰 변경 사항
- SectionService 의 createFirstSection 이 최초 구간 생성이 아니면 예외를 던지도록 변경 최초 구간 생성일때만 호출되어야 하므로 validate 를 수행해주었습니다.
- 전체적인 테스트 네이밍에 부족함과 소홀함을 느껴 피드백 주신 대로 테스트 시 주어진 조건 , 기능 , 의도한 결과를 나타낼 수 있도록 변경하였습니다.
- 구간 삭제 시 거리가 더해지는 테스트 및 인수 테스트에서 노선 , 역 을 찾지 못하는 테스트도 진행하였습니다.
- 서버 예외도 SQL 에러 처럼 로그만 작성하고 안전한 메시지만을 전달하도록 변경했습니다.

2023-07-26 11:11 UTC, Laterality approved these changes
잘 구현해주셨어요.

크게 수정이 필요한 부분은 없어 바로 머지하도록 하겠습니다.

테스트 네이밍에 관해 코멘트 남겨드렸는데요. 한번 확인해주세요~

궁금하신 점은 DM 주셔도 좋습니다.

2023-07-26 11:11 UTC, Laterality commented on src/test/java/subway/domain/SectionsTest.java
> +    @DisplayName("D -> A -> B -> C 구간에서 D -> A ,A -> B의 구간 길이가 각각 10 , 15일 때 A 역을 삭제하면 D -> B 구간 길이가 25가 된다.")
테스트 이름이 전보다 구체적으로 작성된 점은 좋습니다.

다만 테스트를 읽는 입장에서는 길이가 10인지 25인지, 테스트하는 노선이 어떻게 생겼는지보다 **테스트 조건과 결과가 무엇을 의미하는지**에 더 관심을 가질텐데요.

예를 들면 이 테스트의 경우 두 개의 문장으로 설명할 수 있겠네요.

1. "두 구간이 연결된 노선(조건)에서 중간에 위치한 역을 제거(행위)하면 제거된 역의 상/하행역을 새로운 상/하행역으로 하는 구간이 된다(결과)"
2. "두 구간이 연결된 노선(조건)에서 중간에 위치한 역을 제거(행위)하면 합쳐진 구간의 거리는 합쳐진 구간의 거리의 합과 같다(결과)"

테스트 이름에 테스트 내용을 너무 구체적으로 나타낼 필요는 없습니다. 이 테스트가 검증하는 것이 무엇인지 설명하는 형태로 나타내보시면 좋겠어요.

2023-07-26 11:11 UTC, merged

2023-07-26 12:44 UTC, impati commented on src/test/java/subway/domain/SectionsTest.java
> +    @DisplayName("D -> A -> B -> C 구간에서 D -> A ,A -> B의 구간 길이가 각각 10 , 15일 때 A 역을 삭제하면 D -> B 구간 길이가 25가 된다.")
다음 Step 때 반영해보겠습니다!