Step3 : 구간 제거 기능 심화 구현
next-step/spring-subway pull request #37
Opened 2023-07-25 15:14 UTC by worldii

안녕하세요 우테캠 교육생 박종하입니다. 
# step3 
- 구간 제거 심화 구현
  - [x] 구간 삭제 시 ,위치에 상관 없이 삭제가 가능하도록 수정
  - [x] 노선 삭제 시, 연관된 구간 모두 삭제
- 제거가 안되는 경우 에러를 반환
  - [x] 구간이 하나인 노선일 경우.
  - [x] 제거하려는 역이 노선의 구간에 포함되어있지 않는 경우.

# step1_2 
코멘트 관련, 그리고 따로 질문 남겨놓았는데, 답변 해주시면 감사하겠습니다!
https://github.com/next-step/spring-subway/pull/17#discussion_r1271392085
https://github.com/next-step/spring-subway/pull/17#discussion_r1273671576
https://github.com/next-step/spring-subway/pull/17#discussion_r1272951610
https://github.com/next-step/spring-subway/pull/17#discussion_r1273675552
https://github.com/next-step/spring-subway/pull/17#discussion_r1269203794
https://github.com/next-step/spring-subway/pull/17#discussion_r1269306006
https://github.com/next-step/spring-subway/pull/17#discussion_r1269633292

# 관련 질문 
관련 질문은 댓글로 남겨놓겠습니다. 감사합니다.

2023-07-25 15:29 UTC, worldii commented on src/main/java/subway/domain/Line.java
> +    private void validateName(final String name) {
현재는 도메인에서 null 이나, 빈값인 경우 예외처리를 해주고 있습니다. wrapper 클래스로 감쌀지 생각도 해봤지만, 단순 빈값만 validate하는 거면 그냥 처리해도 되지 않을까하여 이렇게 구현하였습니다. 
하지만  빈값이나 null 요청은 비즈니스 로직 validation 이 아니라 요청에 대한 validation이라고 생각하여 요청에 대한 dto에서 해줘야하는게 맞다고 생각합니다. 
하지만, 막상, tdd를 하다보면 도메인 객체 생성을 할때 예외 처리를 생각하게 되는데 dto에서 예외 처리를 하면, 도메인에서는 빈값에 대한 잘못된 요청은 testcode를 짜지 않아도 되는지, 아니면 dto validation, domain validation 둘다 처리를 해줘야 하는지 궁금합니다.

2023-07-25 15:29 UTC, worldii commented on src/main/java/subway/dao/LineDao.java
> +            throw new SubwayException(DUPLICATED_LINE_NAME, e);
1,2단계 때 표준 예외로만 처리하던 방식에서 응답값을 검증하기 위해, 커스텀 예외로 수정하고, 이와 관련한 status와 메세지를 관리하기 위해 enum으로 예외 코드를 처리하였습니다.  dao 에서 중복된 것을 넣을 때, 이는 사용자 입력의 잘못이라고 생각하여 bad Request, 그리고 나머지 sql오류는 사용자 예외가 아닌 db문제가 있을 수 있다고 생각하여, internal server error 를 띄웠습니다. 커스텀 예외를 따로 정의하고 나니, dao 에서 표준예외로 던져진 것을 어디까지 커스텀 예외로 바꿔야 할까에 대한 고민이 생겼습니다. 이에 대한 기준이 있는지 궁금합니다.

2023-07-25 15:29 UTC, worldii commented on src/main/java/subway/application/LineService.java
> +        sectionDao.deleteSections(line.getSections().getSections());
현재 라인 서비스에서 라인을 찾고, 라인에 대한  sections를 모두  삭제, 그리고 라인 삭제하는 방식으로 구현하였습니다. 
직접 참조의 방식 때문인지 dao가 다소 커진 느낌을 받아서, 어떻게 dao test code를 해야할지 고민이었는데, dao test는 결국 짜지 못하였습니다.  다음과 같은 서비스같은 경우, dao 동작이 잘 동작한다는 가정하에 제작하여 따로 테스트를 안했는데, 서비스 테스트를 짜는것이 맞을까요..? 고민이 듭니다.

2023-07-26 15:54 UTC, yjksw requested changes
안녕하세요 종하님 🙇‍♀️
리뷰 적용과 3단계 구현 잘 해주셨어요 ! 
몇가지 코멘트 남겼는데 확인 부탁드립니다 ㅎㅎ
그리고 남겨주신 댓글에 대한 코멘트도 차차 추가하겠습니다 ~!

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/application/LineService.java
> +    @Transactional(readOnly = true)
메서드마다 `@Transactional` 을 추가하는 것이 번거로우니,
클래스 최상단에 `@Transactional(readOnly = true)` 를 추가해두고 변경이 발생하는 메서드에만 `@Transactional` 을 추가로 달아주기도 합니다😊

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/application/LineService.java
> +        sectionDao.deleteSections(line.getSections().getSections());
그랬군요 ! 
DAO가 복잡하다면, 테스트가 꼭 필요한 것 같아요. 오히려 간단한 select 등등 인 경우에는 테스트하지 않기도 합니다 ㅎㅎ 
dao test를 하는데 어려웠던 이유는 무엇이었나요 ?

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/dao/LineDao.java
> +            throw new SubwayException(DUPLICATED_LINE_NAME, e);
먼저 이미 알고 계실테지만, 표준 예외로 던져진 것들 커스텀 예외로 바꾸는 것은 필수는 아니에요 ㅎㅎ
그래서 모든 표준 예외 어디까지 바꿔야하는지는 고민하지 않아도 됩니다. 

하지만, 알고 있는 발생 가능한 예외를 모두 핸들링 해야한다는 질문으로 바꿔본다면, 모두 핸들링 해야합니다 ! 
애플리케이션에 발생 가능한 예외를 모두 파악하고, 발생 시 어떻게 처리할지는 모두 구현되어 있어야 해요

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/domain/Line.java
> +    private void validateName(final String name) {
먼저 말씀해주신 부분이 모두 맞습니다 ㅎㅎ 
단순 빈 값 또는 null 유효성 책임은 요청 객체에서 충분히 가져도 되어요.

하지만 그렇다고 도메인에서 그 책임을 전혀 지지 않아도 되는 것은 아니랍니다.
요청 객체는 변화가 잦고 언제든지 교체될 수 있는 부분이고, 도메인은 외부 환경과 상관없이 필요한 유효성을 꼭 보장해야하기 때문이에요.

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/domain/Section.java
> +    public Section add(final Section newSection) {
section을 합치는 것이니 merge라는 표현을 써도 좋겠네요 😊

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/domain/Sections.java
> +    private final Set<Station> cache;
cache 보다, 어떤 데이터를 담고 있는 것인지 구체적으로 적어주는 것이 좋아요 ㅎㅎ
지금은 애플리케이션이 다소 간단하지만, 점점 코드량이 많아질수록 이런 네이밍으로 인한 오류가 속도저하가 꽤 많이 발생한답니다.

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/domain/Sections.java
> +        });
```suggestion
        findMatchingOneSection(section).ifPresent(oneMatchingSection -> {
            newSections.remove(oneMatchingSection);
            newSections.add(oneMatchingSection.subtract(section));
        });
```

요렇게 수정되어야하는 것이죠 ? 🤔

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/domain/Sections.java
> +            newSections.add(reArrangeSection(station));
```suggestion
            newSections.add(rearrangeSection(station));
```

하나의 단어라서 중간에 camelCase 하지 않아도 됩니다 😉

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/domain/Sections.java
>      }
저는 개인적으로 stream에서 있는 람다에서도 줄인말을 잘 쓰지 않는 편이에요.
코드를 파악할 때, 파이프라인을 따라가며 실제로 어떤 값인지 확인해야하기 때문입니다 ㅎㅎ

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/domain/Sections.java
> +        return removeSection;
2-depth네요 !

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/domain/Sections.java
>          }
newSections을 돌면서 일치하는 station이 포함된 것을 찾는 것이 조금 어색하게 느껴지는데요, 혹시 newSections는 어떤 값인가요 ?

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/domain/Station.java
> +    }
비슷한 개념을 수행하는 메서드인 것 같은데 하나는 match, 다른 하나는 isNotEqual이군요 ! 
한번 용어를 통일해도 좋을 것 같아요.
이 코드를 보는 다른 사람은 반대 개념이 아니라고 생각할 수도 있을 것 같네요 ~!

2023-07-26 15:54 UTC, yjksw commented on src/main/java/subway/exception/ErrorCode.java
> +public enum ErrorCode {
커스텀 예외를 구현하고, enum으로 에러 메시지를 관리해서 얻은 장점과 단점은 무엇인가요 ? ㅎㅎ

2023-07-26 15:54 UTC, yjksw commented on src/main/resources/test.sql
> +insert into SECTION (up_station_id, down_station_id,line_id,distance) values (2L, 3L, 1L, 10 );
공통 테스트 픽스처를 관리했을 때 장점과 단점도 고민해보면 좋을 것 같아요 😊
테스트에서 무엇보다 중요한 것은 테스트 간 격리랍니다 !

2023-07-26 15:54 UTC, yjksw commented on src/test/java/subway/dao/SectionDaoTest.java
> +        );
`extracting` 이라는 키워드도 공부해보면 좋을 것 같아요 ~

2023-07-26 16:58 UTC, worldii commented on src/main/java/subway/domain/Sections.java
> +        });
헉 그러네요... 😭

2023-07-26 16:58 UTC, worldii commented on src/main/java/subway/domain/Sections.java
> +    private final Set<Station> cache;
네이밍 수정하겠습니다~!

2023-07-26 16:59 UTC, worldii commented on src/main/java/subway/domain/Sections.java
> +            newSections.add(reArrangeSection(station));
넵 수정하겠습니다!

2023-07-26 17:01 UTC, worldii commented on src/main/java/subway/domain/Station.java
> +    }
용어 통일하겠습니다!! 네이밍 관련 실수가 많네요... ㅠㅠ 앞으로 더 인지하려고 노력해야겠네요

2023-07-26 17:14 UTC, worldii commented on src/main/java/subway/domain/Sections.java
>      }
네이밍 더 신경 쓰도록 하겠습니다..!

2023-07-27 02:28 UTC, worldii commented on src/main/java/subway/domain/Sections.java
>          }
service단에서 sections에 delete하려는 station을 넘겨주게 되면, 해당 station이 포함되어있는 구간을 지우고 새로운 구간을 삽입한 새로운 sections 반환합니다. sections가 불변 객체이므로 newSections를 생성하게 되었습니다.

2023-07-27 02:41 UTC, worldii commented on src/main/java/subway/domain/Sections.java
> +        return removeSection;
stream을 활용하여 리팩토링 하도록 하겠습니다.

2023-07-27 02:56 UTC, worldii commented on src/main/java/subway/domain/Sections.java
>          }
다른 좋은 방법이 있을까요? 리팩토링시 가독성 있게 고쳐보려고 노력하겠습니다.

2023-07-27 03:01 UTC, worldii commented on src/main/java/subway/exception/ErrorCode.java
> +public enum ErrorCode {
에러들을 한곳에서 상태관리 할 수 있다는 점, 쉽게 추가 가능한 점이 장점일거같습니다. 한편으로는  굳이 커스텀으로 표현하지 않아도 충분히 의미 전달이 되는데 불필요하게 사용하는 것이 아닌가.. 라는 고민이 되었습니다. 리뷰어  님의 의견이 궁금합니다.

2023-07-27 06:00 UTC, worldii commented on src/main/resources/test.sql
> +insert into SECTION (up_station_id, down_station_id,line_id,distance) values (2L, 3L, 1L, 10 );
현재 메서드마다는 격리가 되어있는 것으로 아는데,  너무 테스트 데이터에 의존적인것 같다는 생각을 하였습니다. 따라서 조회를 제외하고는 given 절에서 생성하도록 리팩터링하겠습니다.

2023-07-27 06:08 UTC, worldii commented on src/main/java/subway/application/LineService.java
> +        sectionDao.deleteSections(line.getSections().getSections());
section Dao 를 테스트 하기 위해, 현재 사용하지 않는 메서드(조회)들을 만드는 것이 맞나 고민이 되었고, 테스트 디비를 따로 분리하기 위해 어떤 방식으로 진행할지 몰라 어려움을 겪었던 것 같습니다.

2023-07-27 16:18 UTC, worldii commented on src/main/java/subway/application/LineService.java
> +        sectionDao.deleteSections(line.getSections().getSections());
현재는 spring boot test말고도 인메모리 디비로 테스트 할수있음을 알았고, 이에 대해 학습을 진행하였습니다!! select에 대한 고민은, 테스트 격리를 위해서면 만드는게 맞다고 판단하여 만들었습니다!

2023-07-28 01:42 UTC, worldii commented
추가 리팩터링
피드백 반영 (네이밍 같은 사소한 변경)
테스트 픽스쳐 격리 위해, 리팩터링
관련 질문은 댓글로 남겨놓았습니다! 감사합니다.!!!!

2023-07-28 06:04 UTC, yjksw approved these changes
안녕하세요 😊
리뷰 적용해주신 것 잘 확인했습니다 ~! 
질문들에 대한 답변도 달아놓았으니 확인 부탁드려요

2023-07-28 06:04 UTC, yjksw commented on src/main/java/subway/domain/Sections.java
>          }
이름이 newSection이 아니라면 조금 더 의미가 잘 전달될 수 있을 것 같아요 ! 

예를 들어, 
```
originalSections.stream()
  .filter(section -> section.matchOneStation(station))
  .collect(toList());
```

요렇게 해보면 조금 더 나아지려냐요 ? ㅎㅎ

2023-07-28 06:04 UTC, yjksw commented on src/main/java/subway/exception/ErrorCode.java
> +public enum ErrorCode {
그렇군요 ! 말씀하신 것처럼 발생 가능한 에러를 한 곳에서 확인할 수 있다는 장점이 있을 수 있겠네요.

저는 개인적으로 표준 예외를 사용하는 편입니다. 
왜냐하면 표준 예외는 자바를 사용하는 대부분의 개발자가 알고 있는 것이라서 이미 싱크가 맞춰져 있고, 
이 예외가 대략 어느 맥락에서 발생한 것인지 모두 인지하고 있기 때문이에요. 
(예를 들어, IllegalArgument는 어떤 외부값에 의한 것임을 이미 다 알고 있죠) 

하지만 커스텀 예외는 새롭게 만들어진 객체이므로 어떤 것인지 파악이 필요하고,
오히려 더 자세하게 나뉘어져 있는 표준 예외보다 상위에서 단 하나의 예외만 쓰이고 있는 부분도 있는 것 같아요.

그리고 말씀하신대로 메시지로 이미 잘 표현할 수 있기도 한 것 같습니다 ㅎㅎ

2023-07-28 06:04 UTC, yjksw commented on src/test/java/subway/dao/LineDaoTest.java
> +public class LineDaoTest {
다양한 [테스트 기법](https://pomo0703.tistory.com/100) 이 있으니 적용해보아도 좋을 것 같아요 ~ 
생각보다 스프링이 많은 것을 제공해준답니다 ㅎㅎ

2023-07-28 06:04 UTC, yjksw commented on src/test/java/subway/dao/LineDaoTest.java
> +
given을 메서드 내에서 확인할 수 있는 것이 좋군요 !

2023-07-28 06:04 UTC, merged