[step2] 경로 조회 기능 PR 요청
next-step/spring-subway pull request #63
Opened 2023-09-16 18:10 UTC by jisoo27

안녕하세요 리뷰어님! 너무 늦게 리뷰를 부탁드려 죄송합니다😅
늦었지만 잘 부탁드리겠습니다.🙇🏻‍♀️

2023-09-18 04:24 UTC, boorownie requested changes
안녕하세요 지수님! 오랜만입니다.
끝까지 미션을 진행해주셔서 감사합니다 :)
저도 최선을 다해서 리뷰하겠습니다!

미션을 수행하시면서 다양한 고민을 하신게 보이는 미션 수행이였습니다 👍 
몇 가지 코멘트를 남겨놓았는데 한번 같이 고민해보시고 반영해보세요~

2023-09-18 04:24 UTC, boorownie commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:datajdbc;MODE=MySQL
메모리 디비로 설정하셨군요 👍

2023-09-18 04:24 UTC, boorownie commented on src/main/java/subway/domain/Sections.java
> +    public List<Section> getSectionList() {
자료구조를 의미하는 네이밍의 경우 해당 자료구조에 종속적인 네이밍이 될 수 있습니다.
```suggestion
    public List<Section> getSections() {
```

2023-09-18 04:24 UTC, boorownie commented on src/main/java/subway/application/LineService.java
> +                .map(line -> LineResponse.of(line, line.getSections().findAllStation()))
LineService에서 line에 Sections가 있는지, Sections에 findAllStation이 있는지를 알게 할 필요는 없을 것 같고
만약 findAllStation의 네이밍이 변경되면 그 영향이 LineService에도 전파가 될 수 있습니다.
LineResponse.of(line) 으로 원하는 동작을 수행할 순 없을까요?

2023-09-18 04:24 UTC, boorownie commented on src/main/java/subway/application/LineService.java
> +        List<Station> allStation = sections.findAllStation();
line에서 해당 Line에 속해있는 모든 Station 목록을 조회하는 메서드가 있다면 어떨까요?

2023-09-18 04:24 UTC, boorownie commented on src/main/java/subway/application/PathFindService.java
> +    private final LineDao lineDao;
Dao에 의존하는 것과 Service에 의존하는 차이가 있거나 선택하는 기준은 무엇인가요?
둘 다 하나의 계층에 의존하는 것과는 어떤 차이가 있을까요?

2023-09-18 04:24 UTC, boorownie commented on src/main/java/subway/domain/Sections.java
> +public class Sections {
일급 컬렉션 클래스 활용 👍

2023-09-18 04:24 UTC, boorownie commented on src/main/java/subway/domain/Path.java
> +    private int charge;
Path가 Stations가 아닌 Sections를 가지고 있다면 
distance나 charge를 변수로 가지고 있을 필요는 없을 것 같은데 어떻게 생각하시나요?

2023-09-18 04:24 UTC, boorownie commented on src/main/java/subway/domain/DijkstraPathFinder.java
> +public class DijkstraPathFinder implements PathFinder{
DijkstraPathFinder가 스프링 빈으로 등록이 되어야 하나요?

2023-10-02 12:05 UTC, jisoo27 commented on src/main/java/subway/application/PathFindService.java
> +    private final LineDao lineDao;
혹시 이 부분에 대해서 제가 참고해서 공부해볼 수 있는 자료를 도움 받을 수 있을까요? 이 부분에 대해서 고민해 보고, 공부해보았는데도 잘 감이 오지 않습니다 ㅜㅜ ..

2023-10-02 13:04 UTC, jisoo27 commented on src/main/java/subway/application/PathFindService.java
> +    private final LineDao lineDao;
Dao 를 반복해서 사용하게 되면 데이터 무결성을 지키기 위한 검증 들이 불 필요하게 늘어나는 문제가 발생할 수 있습니다. 서비스 계층을 의존하게 되면 트랜잭션에 대한 처리 까지 보장할 수 있어서 좋지만, 서비스 계층 간 순환참조가 일어나게 될 수 도 있기 때문에 주의해야 합니다.

2023-10-04 05:06 UTC, boorownie requested changes
안녕하세요! 회신이 조금 늦었네요ㅠ
피드백 잘 구현해주셨습니다 👍 
기능적으로 한 가지 확인해주셔야 할 것이 있어서 가볍게 코멘트 남겼는데 확인 한번 부탁드려요~

2023-10-04 05:06 UTC, boorownie commented on src/main/java/subway/application/LineService.java
> +                .map(LineResponse::of)
코드 간소화 👍

2023-10-04 05:06 UTC, boorownie commented on src/main/java/subway/application/PathFindService.java
> -    private final LineDao lineDao;
아키텍처 계층 통일 👍

2023-10-04 05:06 UTC, boorownie commented on src/main/java/subway/application/PathFindService.java
> +        return new PathResponse(createStationResponse(path.getStations()), path.getSections().getSections().get(0).getDistance(), path.getSections().getSections().get(0).getCharge());
```
path.getSections().getSections().get(0).getDistance()
```

디미터 법칙을 고려해서 개선해 볼 수 있을 것 같아요 :)

2023-10-04 05:06 UTC, boorownie commented on src/main/java/subway/application/PathFindService.java
> +        return new PathResponse(createStationResponse(path.getStations()), path.getSections().getSections().get(0).getDistance(), path.getSections().getSections().get(0).getCharge());
```
path.getSections().getSections().get(0).getCharge()
```

이 코드는 sections의 운임이 아니라 sections의 첫 구간에 대한 운임을 구하는 것 아닌가요?

2023-10-04 05:06 UTC, boorownie commented on src/main/java/subway/domain/Section.java
> +    }
생각해보면 구간(Section)의 운임이 아니라 구간 목록(Sections)의 운임이어야 할 것 같은데 맞나요?

2023-10-10 00:13 UTC, boorownie approved these changes
고생 많으셨습니다! 피드백을 완벽히 잘 반영해주셨네요
교육이 끝나고 시간이 조금 흘렀지만 끝까지 포기하지 않고 시도해주셨군요 멋집니다!
이 과정이 지수님께 도움이 되셨길 바라봅니다.
이만 머지하겠습니다 👍

2023-10-10 00:13 UTC, boorownie commented on src/main/java/subway/domain/Sections.java
> +    public int calculateCharge(int distance) {
피드백 반영 👍

2023-10-10 00:13 UTC, merged

2023-10-10 06:29 UTC, jisoo27 commented on src/main/java/subway/domain/Sections.java
> +    public int calculateCharge(int distance) {
끝까지 리뷰해주셔서 정말 감사합니다 😃