Step2. 경로조회기능_yg
next-step/spring-subway pull request #7
Opened 2023-05-26 10:53 UTC by yonggyujeong

안녕하세요 리뷰어님!

[thread-safe]
지난번 리뷰에서 말씀해주신, 멀티스레드 환경에서의 상태를 가진 빈의 테스트를 적용하고, thread-safe 하도록 concurrent~ 타입으로 변경하였습니다. 덕분에 `thread-safe 함에 대해 확실히 깨닫게 되었습니다`. 좋은 리뷰 감사합니다! 🙏 이번 미션에도, jgrapht를 thread-safe 한 타입으로 생성할 수 있었습니다.

[테스트 데이터 준비]
그리고, 말씀해주셨던, `테스트 데이터 준비`관련해서 data.sql을 지우고, 테스트 내에서 테스트 데이터를 만들도록 하였습니다! 🙏

[원시값 포장]
그리고 이번 미션을 하면서 궁금한 점이 하나 있습니다.
바로 원시값 포장 VO 객체에 대한 것입니다. 기존에 거리값을 Integer 값을 가지는 Distance 객체를 만들어서 사용하고 있었습니다.
하지만 이번 미션을 하면서, double 타입의 distance객체가 필요했고, distance의 거리 값을 double로 바꾸려고 하니, 기존에는 integer 타입으로 썻던 코드를 전부 변경해야하는 상황이 생겼습니다... 결국 이번 기능에서 추가된 것들은 Distance 객체를 사용하지 못하고, double 타입의 기본 값을 쓰게 되었습니다.

원시값의 포장이라는 것이 객체지향적이긴 해도 불편한 것 같은데... 실무에서 사용하는 개념인지.. 여쭈어보고 싶습니다.

좋은 리뷰 감사드립니다!

2023-05-27 08:55 UTC, ecsimsw requested changes

2023-05-27 08:55 UTC, ecsimsw commented on src/main/java/subway/config/exceptionHandle/ExceptionAdvice.java
> +        return ErrorResponse.of(HttpStatus.INTERNAL_SERVER_ERROR, generateLogId(ex), ex);
HttpStatus.INTERNAL_SERVER_ERROR의 에러 메시지가 그대로 노출될 것 같아요!!
에러 메시지가 사용자에게 그대로 노출되면 위험한 상황이 있지 않을까요? 어떤 상황을 주의해야 할까요?

2023-05-27 08:55 UTC, ecsimsw commented on src/main/java/subway/domain/SubwayGraph.java
> +    private Map<Station, Set<Section>> connection = new ConcurrentHashMap<>();
👍😊

2023-05-27 08:55 UTC, ecsimsw commented on src/main/java/subway/config/exceptionHandle/ErrorResponse.java
> +                .code(Integer.toString(code.value()))
오홍 에러 응답으로 응답 바디에 상태 코드를 함께 담아주고 있군요!!

저도 이런 꼴을 많이 봤어요.
이건 다른 곳에서 어떻게 쓰는지 모르겠지만 개인적으론 반대하는 패턴이에요. 
이 API를 사용하는 사용자는 httpStatus 자체와 바디의 응답 코드 중 어떤 것을 더 믿어야할까요?
예를 들면 아래 같은 꼴로요!
```
@ExceptionHandler(AuthenticationException.class)
@ResponseStatus(HttpStatus.UNAUTHORIZED)
public ErrorResponse handleAuthenticationException(AuthenticationException ex) {
   return ErrorResponse.of(HttpStatus.BAD_REQUEST, generateLogId(ex), ex);
}
```

이런 꼴로 응답하는 경우도 많이 봐서 어떤게 정답이다라고 말하긴 뭐하지만 제 생각을 공유해보고 싶었어요.
혹시 용규님이 생각하시는 응답 바디에 상태 코드를 갖고 있는 것의 장점이 있다면 말씀해주시겠어요?

2023-05-27 08:55 UTC, ecsimsw commented on src/main/java/subway/domain/searchGraph/JgraphtSearchGraph.java
> +        DijkstraShortestPath dijkstraShortestPath = new DijkstraShortestPath(graph);
findShortenPath()는 많이 호출되는 메서드일 것 같아요!! 
그때마다 DijkstraShortestPath를 매번 생성하는 꼴일거 같은데 미리 한번만 생성해두면 어떨까요?

2023-05-27 08:55 UTC, ecsimsw commented on src/main/java/subway/domain/searchGraph/JgraphtSearchGraph.java
> +        return SubwayPath.of(graphPath.getVertexList(), graphPath.getWeight());
저는 변수는 가급적 생명이 짧도록 하는 것을 좋아해요. 사용처와 선언처를 가급적 가깝게 하는 편입니다.

이 부분의 graphPath도 마찬가지였습니다. 
가급적 null이 발생할 수 있는 위치와 null 처리를 멀면 지금은 짧은 코드라서 null이 발생할 수 있겠다는 생각이 눈에 잘보이지만 80번~84번 줄 사이까지의 코드가 많아지면 다른 팀원들은 놓치기도 좋고, 나중에 리팩토링할 때도 graphPath의 선언 부를 따라가서 graphPath이 어떤 값이 대입되었고 왜 null 처리가 필요하구나를 확인해야할 것 같다는 생각입니다.

``` java
try {
  GraphPath graphPath = dijkstraShortestPath.getPath(startStation, endStation);
  if (graphPath == null) {
   throw new IllegalArgumentException(SEARCH_GRAPH_CANNOT_FIND_PATH);
  }
   return SubwayPath.of(graphPath.getVertexList(), graphPath.getWeight());
} catch (IllegalArgumentException e) {
   throw new IllegalArgumentException(SEARCH_GRAPH_NOT_CONTAINS_STATION, e);
}
```

그냥 제 취향인데 이런 생각을 하는 사람도 있다~ 느낌으로 공유해보았습니다 ㅎㅎ
반영하지 않으셔도 됩니다 😁

2023-05-27 08:55 UTC, ecsimsw commented on src/main/java/subway/domain/vo/SubwayPath.java
> +    private final Double distance;
딱 이 부분이 PR 바디의 원시값 포장에 대한 제 답이 될 것 같습니다!

지금 상황에서 SubwayPath의 distance에 -1이 값으로 담기면 어떻게 될까요? 
SubwayPath라는 객체는 문제없이 생성될 것 같은데 그렇게되면 다음 작업자는 SubwayPath를 완전히 믿고 로직을 짤 수 없을 것 같습니다. 

예를 들면 distance를 활용하는 메서드를 만들 때마다 아래처럼 distance의 유효함을 확인해야할 것 같습니다. 
```
public void A() {
  if(subwayPath.distance < 0) {
     throw new IllegalArgumentException("")
  }
  // .. 
}
```

만약 Distance가 포장되어 있었으면 SubwayPath의 distance는 유효함을 믿고 다른 로직들을 만들어 갈 수 있겠네요!
```
 public class SubwayPath {
     private final List<Station> stations;
     private final Distance distance;
     private Fare fare;
}
```

또 비슷한 얘긴데 저는 관리에도 더 편할 것 같은게 Station의 이름이 적어도 3글자 이상이라는 조건이 추가되면 어떤 코드를 봐야할까요? 지금은 Station을 따라가 String name 필드를 확인해야할 것 같은데, 만약 StationName이라는 클래스로 포장되어 있었다면 바로 그 부분에서 요구 사항을 수정하면 되겠다는 생각을 할 수 있겠네요.

포장을 하게 되면 Fare에서 해주신 것처럼 값 자체를 초기화하고 계산에 사용하는 것처럼 쓸 수도 있겠고요! `Fare.fromDistance(distance);`

추가로 지금 상황은 정말 많이 나오는 상황일거 같아요. Distance를 Integer로 받는게 더 편하고, 지금까지 그렇게 해왔는데 갑자기 double로 value가 바뀌다니.

아니면 생성자를 하나 더 열면 어떨까요? 

``` java 
public class Distance implements Comparator<Distance> {
    private final Double value;

    public Distance(Double distance) {
        validatePositive(distance);
        this.value = distance;
    }

    public Distance(Integer distance) {
        this(Double.valueOf(distance));
    }
```

2023-05-27 08:55 UTC, ecsimsw commented on src/main/resources/application-test.properties
> +spring.datasource.username=sa
실행 환경별로 설정 파일을 따로!!! 👏 👏 👏

2023-05-27 08:55 UTC, ecsimsw commented on src/main/java/subway/domain/application/SubwayGraphService.java
removeStation에는 Transactional 처리가 없어도 될까요?

2023-05-27 17:19 UTC, yonggyujeong reviewed
좋은 리뷰 주셔서 많이 배웠습니다! 감사합니다!

혹시 실례가 안된다면.. 개발 하면서 이책은 정말 좋았다! 라고 생각한 도서가 있다면 추천.. 부탁드려도 될까요.. 꼭 읽어보겠습니다..감사합니다!!

2023-05-27 17:19 UTC, prebird commented on src/main/java/subway/config/exceptionHandle/ErrorResponse.java
> +                .code(Integer.toString(code.value()))
오.. 그냥 당연히 응답코드를 담아야겠다고 생각했는데, httpStatus자체로 응답코드를 정해주니, 리뷰어님 말씀대로 굳이 바디에 담을 필요가 없을 것 같네요👍 저도 구현 하면서 @ResponseStatus 와 바디 둘다 값을 담으니, 불편하다고 생각했는데, 말씀하신대로 만약에라도 다른 값을 담을 경우 클라이언트가 헷갈릴 수도 있을 것 같네요. 수정해서 반영했습니다! 감사합니다

2023-05-27 17:19 UTC, prebird commented on src/main/java/subway/domain/searchGraph/JgraphtSearchGraph.java
> +        DijkstraShortestPath dijkstraShortestPath = new DijkstraShortestPath(graph);
그렇네요.. DijkstraShortestPath 에 파라메터로 담는 graph가 참조 타입이니, 굳이 요청 받았을 때 생성할 필요가 없겠네요! 미리 한번만 생성하도록 수정했습니다 감사합니다!

2023-05-27 17:19 UTC, prebird commented on src/main/java/subway/domain/application/SubwayGraphService.java
감사합니다 수정했습니다!

2023-05-27 17:19 UTC, prebird commented on src/main/java/subway/config/exceptionHandle/ExceptionAdvice.java
> +        return ErrorResponse.of(HttpStatus.INTERNAL_SERVER_ERROR, generateLogId(ex), ex);
오.. 그렇군요. 에러메세지를 반환한 목적은 프론트엔드에 자세한 에러의 원인을 제공해 주고 싶어서 그랬는데, 생각해보니 서버에러는 자세한 내막을 프론트엔드에서 알 필요는 없겠군요.. 그리고 자세한 서버 에러를 노출할 경우에, 내부 구현이 외부에 노출되어 보안상의 취약점이 될 것 같네요! 해당 내용 수정하도록 하겠습니다! 감사합니다

2023-05-27 17:19 UTC, prebird commented on src/main/java/subway/domain/searchGraph/JgraphtSearchGraph.java
> +        return SubwayPath.of(graphPath.getVertexList(), graphPath.getWeight());
리뷰어님 말씀대로 하면 더 가독성이 높고 유지보수하기 편한 코드가 될 것 같네요! 경험 공유 감사합니다! 적극 반영하겠습니다!👍

2023-05-27 17:19 UTC, yonggyujeong commented on src/main/java/subway/domain/vo/SubwayPath.java
> +    private final Double distance;
오.. 그렇네요! 원시값을 포장하면 해당 값과 연관된 행위를 캡슐화 하여 같이 관리할 수 있고, 새로운 요구사항 반영에도 유연하게 대처할 수 있게 되겠군요! 말씀해주신 대로 값에 대한 유효성 검증도 객체 내부에서 진행되니, 믿을 만한 값이 될 것 같구요! 제가 여쭤본 문제도 생성자를 하나 더 열면 해결되겠네요!

그리고 다른 하나의 문제는 getValue()를 했을때 인수가 같으니 중복정의가 안된다는 점인데.. 이건 그냥 getIntValue(), getDoubleValue() 로 메서드 명을 변경하는 것으로 해결했습니다.

친절한 리뷰 감사드립니다! 덕분에 객체 지향의 장점에 대해 한번 더 깨닫고 갑니다....👍

2023-05-28 08:31 UTC, ecsimsw commented on src/main/java/subway/config/exceptionHandle/ExceptionAdvice.java
> +        return ErrorResponse.of(HttpStatus.INTERNAL_SERVER_ERROR, generateLogId(ex), ex);
👏👏👏👏

2023-05-28 08:31 UTC, ecsimsw commented on src/main/java/subway/domain/searchGraph/JgraphtSearchGraph.java
> +        DijkstraShortestPath dijkstraShortestPath = new DijkstraShortestPath(graph);
최고예요!

2023-05-28 09:17 UTC, ecsimsw approved these changes
음 저는 책보다 코드를 많이 보는 편인 것 같아요.
다른 저장소들 염탐하는 것도 좋아하고, 지금처럼 천천히 코드 읽으며 리뷰하거나 받으면서 서로 생각 공유하는 시간들을 되게 좋아하는 것 같습니다.

혹시 리뷰하거나 리뷰 받을 기회가 많지 않다면, 사람들한테 잘 알려진 프로젝트 코드를 구경하는 건 어떠실까요?

real world 프로젝트라고 아시나요? 각 기술들 조합마다 예제 프로젝트를 구현해서 예시 코드를 제공하는 그런  프로젝트인데 원하시는 기술 스택에 해당하는 저장소를 찾아 코드 한번 참고해보시면 되게 좋은 공부가 될 것 같습니다.

`https://github.com/gothinkster/realworld`

2023-05-28 09:17 UTC, ecsimsw commented on src/main/java/subway/config/exceptionHandle/ExceptionAdvice.java
> +        return ErrorResponse.of(generateLogId(ex), new Exception(INTERNAL_SERVER_ERROR_MESSAGE));
👏

2023-05-28 09:17 UTC, ecsimsw commented on src/main/java/subway/domain/vo/SubwayPath.java
> +    private Fare fare;
fare도 final 처리가 가능하겠네요 ㅎㅎ

2023-05-28 09:17 UTC, ecsimsw commented on src/main/java/subway/config/exceptionHandle/ExceptionAdvice.java
> +        log.error("## error : {}, {}", uuid, ex.getClass().getSimpleName(), ex);
용규님 이건 이미 아시는데 연습이라 아마 log를 error로 다 처리하신 것 같지만... 혹시 노파심에 말씀드리면!!

지금 Bad request와 AuthenticationException, 그리고 확인되지 않은 Exception 이 세개가 log.error로 동일하게 관리되고 있어요.

Bad request와 AuthenticationException는 사용자 측의 실수니 엄청 많이 발생하고, 또 그렇게까지 중요한 정보는 아닐겁니다.  
반면 '확인되지 않은 서버 측 Exception'은 서버 로직의 문제나 상태의 문제로 빠르게 수정되어야 하는 경우를 포함되고 있어서 앞선 두  에러들과는 다른 타입으로 관리되어야 할 것 같습니다.

이게 단순히 콘솔에 출력되는 것이 끝이 아니라 log 타입에 따라 파일에 저장하거나, 알림이 발생하거나, 모니터링 시스템에 올라가는 등 다르게 처리하기 때문에 log의 타입을 잘 나눠주는 것이 엄청 중요합니다.

2023-05-28 09:35 UTC, merged